# -*- coding: utf-8 -*-
"""model_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgVzvcPO86T44AoAD-MmfrF-wSg0GYZv
"""

import os
import random
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_restx import Api, Resource, fields
from werkzeug.middleware.proxy_fix import ProxyFix
import pickle
import numpy


app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)


db_uri = 'sqlite:///{}/prods_datos.db'.format(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = db_uri
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
db.init_app(app)


api = Api(
    app,
    version='1.0', title='API REST',
    description='API REST para el Modelo de Ciencia de Datos',
)


ns = api.namespace('predicciones', description='predicciones')


from db_models import Prediction
db.create_all()


observacion_repr = api.model('Observacion', {
    'sepal_length': fields.Float(description="Longitud del sépalo"),
    'sepal_width': fields.Float(description="Anchura del sépalo"),
    'petal_length': fields.Float(description="Longitud del pétalo"),
    'petal_width': fields.Float(description="Anchura del pétalo"),
})


classified_observation = api.model('ObservacionCalificada', {
    'sepal_length': fields.Float(description="Longitud del sépalo"),
    'sepal_width': fields.Float(description="Anchura del sépalo"),
    'petal_length': fields.Float(description="Longitud del pétalo"),
    'petal_width': fields.Float(description="Anchura del pétalo"),
    'class': fields.String(description='Clase real de la flor')
})


predictive_model = pickle.load(open('simple_model.pkl','rb'))


@ns.route('/', methods=['GET', 'POST'])
class PredictionListAPI(Resource):
    """ Manejador del listado de predicciones.
        GET devuelve la lista de predicciones históricas
        POST agrega una nueva predicción a la lista de predicciones
    """

    # -----------------------------------------------------------------------------------
    def get(self):
        """ Maneja la solicitud GET del listado de predicciones
        """

        return [
            marshall_prediction(prediction) for prediction in Prediction.query.all()
        ], 200

    @ns.expect(observacion_repr)
    def post(self):
        """ Procesa un nuevo recurso para que se agregue a la lista de predicciones
        """

        prediction = Prediction(representation=api.payload)


        model_data = [numpy.array([
            prediction.sepal_length, prediction.sepal_width,
            prediction.petal_length, prediction.petal_width,
        ])]
        prediction.predicted_class = str(predictive_model.predict(model_data)[0])
        print(prediction.predicted_class)

        db.session.add(prediction)
        db.session.commit()

        # Formar la respuesta de la predicción del modelo
        response_url = api.url_for(PredictionAPI, prediction_id=prediction.prediction_id)
        response = {
            "class": prediction.predicted_class,  # la clase que predijo el modelo
            "url": f'{api.base_url[:-1]}{response_url}',  # el URL de esta predicción
            "api_id": prediction.prediction_id  # El identificador de la base de datos
        }

        return response, 201



@ns.route('/<int:prediction_id>', methods=['GET', 'PUT', 'PATCH'])
class PredictionAPI(Resource):
    """ Manejador de una predicción particular
    """

    # -----------------------------------------------------------------------------------
    @ns.doc({'prediction_id': 'Identificador de la predicción'})
    def get(self, prediction_id):
        """ Procesa las solicitudes GET de una predicción particular
            :param prediction_id: El identificador de la predicción a buscar
        """

        prediction = Prediction.query.filter_by(prediction_id=prediction_id).first()
        if not prediction:
            return 'Id {} no existe en la base de datos'.format(prediction_id), 404
        else:

            return marshall_prediction(prediction), 200

    @ns.doc({'prediction_id': 'Identificador de la predicción'})
    @ns.expect(classified_observation)
    def put(self, prediction_id):
        """ Este método maneja la actualización de una observación con la clase que
            tiene en la realidad.

            PUT y PATCH realizan la misma operación.
        """
        return self._update_observation(prediction_id)


    @ns.doc({'prediction_id': 'Identificador de la predicción'})
    @ns.expect(classified_observation)
    def patch(self, prediction_id):
        """ Este método maneja la actualización de una observación con la clase que
            tiene en la realidad.

            PUT y PATCH realizan la misma operación.
        """
        return self._update_observation(prediction_id)


    # -----------------------------------------------------------------------------------
    def _update_observation(self, prediction_id):
        """
        """
        prediction = Prediction.query.filter_by(prediction_id=prediction_id).first()
        if not prediction:
            return 'Id {} no existe en la base de datos'.format(prediction_id), 404
        else:

            print('Payload: {}'.format(api.payload))
            return 'Observación actualizada', 200
            # ---------------------------------------------------------------------------


# =======================================================================================
def marshall_prediction(prediction):
    """ Función utilería para transofmrar una Predicción de la base de datos a una
        representación de un recurso REST.
        :param prediction: La predicción a transformar
    """
    response_url = api.url_for(PredictionAPI, prediction_id=prediction.prediction_id)
    model_data = {
        'sepal_length': prediction.sepal_length,
        'sepal_width': prediction.sepal_width,
        'petal_length': prediction.petal_length,
        'petal_width': prediction.petal_width,
        "class": str(prediction.predicted_class)
    }
    response = {
        "api_id": prediction.prediction_id,
        "url": f'{api.base_url[:-1]}{response_url}',
        "created_date": prediction.created_date.isoformat(),
        "prediction": model_data
    }
    return response


# ---------------------------------------------------------------------------------------
def trunc(number, digits):
    """ Función utilería para truncar un número a un número de dígitos dado
        :param digits: El número de digitos a truncar el número
    """
    import math
    stepper = 10.0 ** digits
    return math.trunc(stepper * number) / stepper

CREATE DATABASE pred_inspecciones;
CREATE USER dnl_admin WITH PASSWORD 'admin';
ALTER ROLE dnl_admin SET client_encoding TO 'utf8';
ALTER ROLE dnl_admin SET default_transaction_isolation TO 'read committed';
ALTER ROLE dnl_admin SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE pred_inspecciones TO dnl_admin;

